---
- name: create the admin user
  user: > 
    name="{{ admin_user }}"
    uid="{{ admin_uid }}"
    shell="/usr/bin/zsh"
    group="users"
    groups="floppy,optical,storage,power,network,video,scanner,disk,log,wheel,systemd-journal,vboxsf"
    password="$6$rounds=656000$qU.4NNw0qteGAJ0X$SbVFqqgoWIFwjpH3rftOeecUjMhiB6FJp1ygOId50kH6Hu/zGhi7fiApK7FBjGylY24kg4ARDjh3zli50WZff/"
  tags: bootstrap

- name: add ssh pubkey to ~/.ssh/authorized_keys for the admin user
  authorized_key: user="{{ admin_user }}" key="{{ item }}"
  with_file: ssh_pubkey
  tags: bootstrap

- name: grant full sudo rights to the admin user
  template: src=sudoers.j2 dest="/etc/sudoers.d/10_{{ admin_user }}"
    owner=root group=root mode=0440
    validate="visudo -cf %s"
  tags: bootstrap
