#!/bin/sh
# source env vars
. ~/.zshenv

# sane key repeat rate
xset r rate 180 40

# no bell
xset -b

# touchpad synaptics
(hash synclient && hash syndaemon) && {
  # horizontal and vertical slow
  synclient VertTwoFingerScroll=1;
  synclient HorizTwoFingerScroll=1;
  # two fingers
  synclient EmulateTwoFingerMinW=5;
  synclient EmulateTwoFingerMinZ=48;
  # disable tapping/scrolling for 2s after key press
  syndaemon -t -k -i -d
}

hash xinput && {
  # natural scrolling
  xinput --set-button-map "AlpsPS/2 ALPS DualPoint TouchPad" 1 2 3 5 4 7 6 8 9 10 11 12;
  # disable stick
  xinput --set-prop "AlpsPS/2 ALPS DualPoint Stick" "Device Enabled" 0;
  # slow down default movement by x3 for precision
  xinput --set-prop "AlpsPS/2 ALPS DualPoint Stick" "Device Accel Constant Deceleration" 3;
  # enabled acceleration by x3 after 6 units
  xset mouse 3 6;
}

# bring back ctrl_alt_backspace
hash setxkbmap 2>/dev/null && { setxkbmap -option ctrl:nocaps -option terminate:ctrl_alt_bksp & }

# left_ptr as standard
hash xsetroot 2>/dev/null && { xsetroot -cursor_name left_ptr & }

# screen layout based on hostname
hash xrandr && {
case "$HOSTNAME" in
  aero) xrandr --output LVDS1 --auto --primary --output VGA1 --auto --above LVDS1 ;;
esac
}

# rehash fonts
[ -d $HOME/.fonts ] && xset +fp $HOME/.fonts
xset fp rehash

# load Xresources
[ -f $HOME/.Xresources ] && xrdb -load $HOME/.Xresources

# set a wallpaper
#hash hsetroot && { hsetroot -fill $HOME/images/wallpapers/current & }
hash hsetroot && { hsetroot -tile $HOME/.wallpapers/current & }

# hide the mouse when not used
hash unclutter 2>/dev/null && { unclutter -noevents & }

# daemons
hash VBoxClient-all 2>/dev/null && { VBoxClient-all & }
hash urxvtd 2>/dev/null && { urxvtd -q -o -f & }
hash mpd 2>/dev/null && { mpd & }
hash dropboxd 2>/dev/null && { dropboxd & }

# start compositing manager
#hash xcompmgr 2>/dev/null && { xcompmgr -c & }
#hash compton 2>/dev/null && { compton & }

# start redshift (lat and long set to Sydney)
hash redshift 2>/dev/null && { redshift -l 33.86:151.20 -t 5700:3600 -g 0.8 -m randr -v & }
# start notification daemons
hash dunst 2>/dev/null && { dunst & }
hash mpdnotify 2>/dev/null && { mpdnotify start & }

# auto-suspend
hash xautolock 2>/dev/null && { xautolock -time 30 -locker "systemctl suspend" -detectsleep & }

# JVM bug
hash wmname 2>/dev/null && wmname LG3D 

# panel
export PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
hash conky 2>/dev/null && { conky > "$PANEL_FIFO" & }
hash panel 2>/dev/null && { panel < "$PANEL_FIFO" & }

# bspwm
#hash sxhkd 2>/dev/null && { sxhkd & }
#exec bspwm -s "$PANEL_FIFO" -p W

# xmonad
exec xmonad
