# Colour Switching
BASE16_SWITCHER="$HOME/Code/bin/base16_switcher_new.sh"
[[ -f $BASE16_SWITCHER ]] && source $BASE16_SWITCHER

# Functions
fpath=( $HOME/.zfuncs "${fpath[@]}" )
autoload -Uz fkill
autoload -Uz fshow

# Prezto
[[ -f ~/.zprezto/init.zsh ]] && source ~/.zprezto/init.zsh

# Update tmux/screen titles
case $TERM in
  screen*)
    precmd(){
      # Restore tmux-title to 'zsh'
      printf "\033kzsh\033\\"
      # Restore urxvt-title to 'zsh'
      print -Pn "\e]2;zsh:%~\a"
    }
    preexec(){
      # set tmux-title to running program
      printf "\033k$(echo "$1" | cut -d" " -f1)\033\\"
      # set urxvt-title to running program
      print -Pn "\e]2;zsh:$(echo "$1" | cut -d" " -f1)\a"
    }
    ;;
esac

# Spacing issue in ZSH / urxvt right-side
export ZLE_RPROMPT_INDENT=1

# Editor-based inline editing - vi mode
set -o vi
bindkey -M vicmd v edit-command-line

# Some annoying defaults
unalias rm 2>/dev/null || true
unalias gb 2>/dev/null || true
setopt clobber

# Change Directory Recent (cdr) functionality
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
#alias cd=cdr

# Dir colors
if hash dircolors 2>/dev/null; then
    eval $(dircolors -b $HOME/.dircolors)
fi

# VMux
export VMUX_GLOBAL=1
export VMUX_EDITOR=nvim
export VMUX_REALEDITOR_NVIM=/usr/local/bin/nvim
export VMUX_NVIM_SESSION_DIR=/tmp

# Local machine mods
if [ -f ~/.zshrc.local ]; then source ~/.zshrc.local; fi

export FZF_COMPLETION_TRIGGER='~~'
#export FZF_DEFAULT_COMMAND='
  #(git ls-tree -r --name-only HEAD ||
      #rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*") 2> /dev/null'
#export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
#export FZF_CTRL_T_OPTS="--height 98% --reverse --border --preview-window right:65% --preview '[[ \$(file --mime {}) =~ binary ]] \
            #&& echo {} is a binary file || bat --color always {} | head -100 2> /dev/null'"
export FZF_ALT_C_COMMAND="bfs -type d -nohidden"
export FZF_DEFAULT_OPTS="--multi"
bindkey -s '\C-p' 'vi $(fzf)\n'
bindkey '\C-g' fzf-cd-widget
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/local/etc/profile.d/z.sh ] && source /usr/local/etc/profile.d/z.sh
[ -f /usr/local/etc/profile.d/fz.sh ] && source /usr/local/etc/profile.d/fz.sh
[ -f /usr/local/etc/profile.d/zsh-interactive-cd.plugin.zsh ] && source /usr/local/etc/profile.d/zsh-interactive-cd.plugin.zsh
[ -f /usr/local/etc/profile.d/zsh-iterm-touchbar.plugin.zsh ] && source /usr/local/etc/profile.d/zsh-iterm-touchbar.plugin.zsh
hash kubectl 2>&- && source <(kubectl completion zsh)

# added by travis gem
[ -f /Users/mbaillie/.travis/travis.sh ] && source /Users/mbaillie/.travis/travis.sh
